# Site settings
title: Nadine K Fischoff
email: nadine.khattak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nadine Fischoff's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: alcajp
github_username:  nadinesk
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
markdown: kramdown
